### your site title here

title: Logan DE JESUS
description: Développeur de jeux vidéos | Programmeur | Chef de Projet | Développement Réalité Virtuelle

baseurl: /me #name of GitHub repository
url: "https://logandej.github.io" #custom url to be used instead of GitHub repository
email: "logan.dejesus1@gmail.com" #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "logan-de-jesus-606b0a172"
# stackoverflow: "#"
github: "logandej"

itchio: "logandej"
youtube: "LoganDJS/videos"
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
# facebook: "#"
# bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

encoding: utf-8

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []



# Defaults automatiques par dossier
defaults:
  - scope:
      path: "_projects/personnels"
    values:
      categorie: personnel
  
  - scope:
      path: "_projects/professionnels"
    values:
      categorie: professionnel
  
  - scope:
      path: "_projects/universitaires"
    values:
      categorie: universitaire

  - scope:
      path: "_projects/gamejams"
    values:
      categorie: gamejam


collections:
  projects:
    output: true

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

